config/urls.py
"""
hxevents URL Configuration
"""

from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("hxevents.pages.urls")),
    path("users/", include("hxevents.users.urls")),
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += (
        staticfiles_urlpatterns()
    )  # tell gunicorn where static files are in dev mode
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=str(settings.MEDIA_ROOT),
    )

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

hxevents/pages/urls.py
from django.urls import path
from .views import home_view, htmx_select_button, htmx_unselect_button

app_name = "pages"

urlpatterns = [
    path("", home_view, name="home"),
    path(
        "htmx/button/select/<int:position>/",
        htmx_select_button,
        name="button-select",
    ),
    path(
        "htmx/button/unselect/<int:position>/",
        htmx_unselect_button,
        name="button-unselect",
    ),
]

hxevents/users/urls.py
from django.urls import path, include

app_name = "users"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
]

hxevents/pages/models.py
from django.db import models

# Create your models here.

hxevents/users/models.py
from django.db import models
from django.contrib.auth import models as auth_models


class User(auth_models.AbstractUser):
    """Utilisateur personnalisé pour l'application."""

hxevents/pages/views.py
from django.template.response import TemplateResponse

MAX_SELECTIONS = 2


def home_view(request):
    return TemplateResponse(request, "pages/home.html")


def htmx_select_button(request, position):
    return TemplateResponse(
        request,
        "pages/fragments/selected-button.html",
        {
            "button_text": request.GET.get("button-text"),
            "position": position + 1,
        },
        headers={"HX-Trigger-After-Swap": "watch-button-selected"},
    )


def htmx_unselect_button(request, position):
    template = (
        "pages/fragments/selected-button.html"
        if position < MAX_SELECTIONS
        else "pages/fragments/unselected-button.html"
    )
    position = position + 1 if position < MAX_SELECTIONS else 0
    return TemplateResponse(
        request,
        template,
        {
            "button_text": request.GET.get("button-text"),
            "position": position,
        },
    )

hxevents/templates/base.html
{% load webpack_loader static %}

<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>{% block title %}{% endblock title %}</title>
    
    {% block head_styles %}
      {% stylesheet_pack 'app' %}
    {% endblock head_styles %} 
    
    {% block head_scripts %}
      <script defer src="https://unpkg.com/htmx.org@1.9.6" integrity="sha384-FhXw7b6AlE/jyjlZH5iHa/tTe9EpJ1Y55RjcgPbjeWMskSxZt1v9qkxLJWNJaGni" crossorigin="anonymous"></script>
      {% javascript_pack 'app' attrs='defer' %}
    {% endblock head_scripts %}
  </head>
  <body class="{% block body_classes %}d-flex flex-column min-vh-100{% endblock body_classes %}">
    {% block messages %}{% include 'partials/messages.html' %}{% endblock messages %}
    
    {% block navigation %}{% include 'partials/navigation.html' %}{% endblock navigation %}
    
    {% block header %}{# placer l'en-tête de la page ici #}{% endblock header %}
    
    {% block outer_content %}
        <main class="flex-grow-1 container">
          {% block content %}{# placer le contenu principal ici #}{% endblock content %}
        </main>
    {% endblock outer_content %}
    
    {% block footer %}{% include 'partials/footer.html' %}{% endblock footer %}
    
    {% block modal %}{# placer vos fenêtres modales ici #}{% endblock modal %}
    
    {% block bottom_scripts %}{# placer vos scripts de bas de page ici #}{% endblock bottom_scripts %}
  </body>
</html>

hxevents/templates/pages/fragments/selected-button.html
<button
  class="btn btn-success mb-3"
  hx-get="{% url 'pages:button-unselect' position %}"
  hx-trigger="click, watch-button-selected from:body"
  hx-swap="outerHTML"
  hx-vals='{"button-text": "{{ button_text }}"}'
>
{{ button_text }}
</button>

hxevents/templates/pages/fragments/unselected-button.html
<button
  class="btn btn-primary mb-3"
  hx-get="{% url 'pages:button-select' position %}"
  hx-swap="outerHTML"
  hx-vals='{"button-text": "{{ button_text }}"}'
>
  {{ button_text }}
</button>

hxevents/templates/pages/home.html
{% extends 'base.html' %}

{% block title %}Home | hxevents{% endblock title %}

{% block content %}
    <div class="container">
        <h1>Welcome to project hxevents</h1>
        <div class="d-flex flex-column align-items-center">
            {% include "pages/fragments/unselected-button.html" with button_text="Bouton 1" position=0 %}
            {% include "pages/fragments/unselected-button.html" with button_text="Bouton 2" position=0 %}
            {% include "pages/fragments/unselected-button.html" with button_text="Bouton 3" position=0 %}
        </div>
    </div>
{% endblock content %}«

hxevents/templates/partials/footer.html
<footer class="mt-auto w-100 bg-dark text-light p-3">
    <div class="container">
        &copy; 2023 Thierry Chappuis
    </div>
</footer>

hxevents/templates/partials/messages.html
<div class="container">
  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-dismissible {% if message.tags %}{{ message.tags }}{% endif %}">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  {% endif %}
</div>

hxevents/templates/partials/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">hxevents</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% url 'pages:home' as url %}
                <li class="nav-item">
                <a class="nav-link {% if request.path == url %}active{% endif %}" {% if request.path == url %}aria-current="page"{% endif %} href="{{ url }}">Home{% if request.path == url %} <span class="visually-hidden">(current)</span>{% endif %}</a>
                </li>
                {% url 'admin:index' as url %}
                <li class="nav-item">
                <a class="nav-link" href="{{ url }}" target="_blank">Admin</a>
                </li>
                {% if not user.is_authenticated %}
                {% url 'users:login' as url %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == url %}active{% endif %}" {% if request.path == url %}aria-current="page"{% endif %} href="{{ url }}">Login {% if request.path == url %} <span class="visually-hidden">(current)</span>{% endif %}</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>